theme: jekyll-theme-modernist
title: H. Emre Bacak's IE423 Fall '23 Progress Journal
description: Hello there, my name is H. Emre Bacak. I created this GitHub Page to keep track of my assignments and projects related to the Fall '23 IE423 course.
